package org.motechproject.mcts.care.common.mds.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.Unique;

import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * MctsTaluk generated by hbm2java
 */
@Entity
@Unique(members = {
        "talukId", "mctsDistrict" })
public class MctsTaluk implements java.io.Serializable {

    
    private static final long serialVersionUID = -226240310604906915L;
    @Persistent
    private MctsDistrict mctsDistrict;
    private int talukId;
    private String name;
    private boolean status;
    /*@Persistent(mappedBy = "mctsTaluk")
    private Set<MctsHealthblock> mctsHealthblocksForTaluk = new HashSet<MctsHealthblock>(
            0);
    @Persistent(mappedBy = "mctsTaluk")
    private Set<MctsVillage> mctsVillagesForTaluk = new HashSet<MctsVillage>(0);*/

    public MctsTaluk() {
    }

    public MctsTaluk(MctsDistrict mctsDistrict, int talukId, String name) {
        this.mctsDistrict = mctsDistrict;
        this.talukId = talukId;
        this.name = name;
    }

    public MctsTaluk(MctsDistrict mctsDistrict, int talukId, String name,
            /*Set<MctsHealthblock> mctsHealthblocksForTaluk,
            Set<MctsVillage> mctsVillagesForTaluk,*/ boolean status) {
        this.mctsDistrict = mctsDistrict;
        this.talukId = talukId;
        this.name = name;
        //this.mctsHealthblocksForTaluk = mctsHealthblocksForTaluk;
        //this.mctsVillagesForTaluk = mctsVillagesForTaluk;
        this.status = status;
    }

    @Field(required = true)
    @Cascade(persist = true, update = true, delete = false)
    public MctsDistrict getMctsDistrict() {
        return this.mctsDistrict;
    }

    public void setMctsDistrict(MctsDistrict mctsDistrict) {
        this.mctsDistrict = mctsDistrict;
    }

    @Field(required = true)
    public int getTalukId() {
        return this.talukId;
    }

    public void setTalukId(int talukId) {
        this.talukId = talukId;
    }

    @Field(required = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Field
    public boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    /*@Field
    public Set<MctsHealthblock> getMctsHealthblocksForTaluk() {
        return this.mctsHealthblocksForTaluk;
    }

    public void setMctsHealthblocksForTaluk(Set<MctsHealthblock> mctsHealthblocksForTaluk) {
        this.mctsHealthblocksForTaluk = mctsHealthblocksForTaluk;
    }

    @Field
    public Set<MctsVillage> getMctsVillagesForTaluk() {
        return this.mctsVillagesForTaluk;
    }

    public void setMctsVillagesForTaluk(Set<MctsVillage> mctsVillagesForTaluk) {
        this.mctsVillagesForTaluk = mctsVillagesForTaluk;
    }*/

}
