package org.motechproject.mcts.care.common.mds.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.Unique;

import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * MctsSubcenter generated by hbm2java
 */
@Entity
@Unique(members = { "subcenterId", "mctsPhc" })
public class MctsSubcenter implements java.io.Serializable {

    private static final long serialVersionUID = -6268048461611026059L;
    @Persistent
    private MctsPhc mctsPhc;
    private int subcenterId;
    private String name;
    private boolean status;
    /*@Persistent(mappedBy = "mctsSubcenter")
    private Set<MctsVillage> mctsVillagesForSubcenter = new HashSet<MctsVillage>(0);
    @Persistent(mappedBy = "mctsSubcenter")
    private Set<MctsHealthworker> mctsHealthworkersForSubcenter = new HashSet<MctsHealthworker>(
            0);*/

    public MctsSubcenter() {
    }

    public MctsSubcenter(MctsPhc mctsPhc, int subcenterId, String name) {
        this.mctsPhc = mctsPhc;
        this.subcenterId = subcenterId;
        this.name = name;
    }

    public MctsSubcenter(MctsPhc mctsPhc, int subcenterId, String name,
            /*Set<MctsHealthworker> mctsHealthworkersForSubcenter,*/ boolean status) {
        this.mctsPhc = mctsPhc;
        this.subcenterId = subcenterId;
        this.name = name;
        // this.mctsVillagesForSubcenterSubCentre = mctsVillagesForSubcenter;
        this.status = status;
    }

    @Field(required = true)
    @Cascade(persist = true, update = true, delete = false)
    public MctsPhc getMctsPhc() {
        return this.mctsPhc;
    }

    public void setMctsPhc(MctsPhc mctsPhc) {
        this.mctsPhc = mctsPhc;
    }

    @Field(required = true)
    public int getSubcenterId() {
        return this.subcenterId;
    }

    public void setSubcenterId(int subcenterId) {
        this.subcenterId = subcenterId;
    }

    @Field(required = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Field
    public boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    /*@Field
    public Set<MctsVillage> getMctsVillagesForSubcenter() {
        return mctsVillagesForSubcenter;
    }

    public void setMctsVillagesForSubcenter(Set<MctsVillage> mctsVillagesForSubcenter) {
        this.mctsVillagesForSubcenter = mctsVillagesForSubcenter;
    }

    @Field
    public Set<MctsHealthworker> getMctsHealthworkersForSubcenter() {
        return mctsHealthworkersForSubcenter;
    }

    public void setMctsHealthworkersForSubcenter(Set<MctsHealthworker> mctsHealthworkersForSubcenter) {
        this.mctsHealthworkersForSubcenter = mctsHealthworkersForSubcenter;
    }*/

}
